### ISSUE TITLE
Ime Insets not restored to correct value when SoftKeyboard gets dimissed by DropDown 

### ISSUE THREAD

**Issue by qrezet** [chrisbanes/accompanist#225] opened 2021-03-04 06:54 UTC
I encountered an issue where I have a form of textfield and a DropDown Menu. 

When I am currently editing a TextField and the SoftKeyboard is showing, and then I click on the DropDown Icon. The Softkeyboard gets dismissed but the padding added by IME insets remains the same.

The only time it gets back to normal is when I focus on the textfield again and the softkeyboard show up, resetting the padding correctly.

**Comment by chrisbanes** [comment] 2021-03-04 09:27
Hmmm, so I just added a `DropdownMenu` to the demo in #226 and it seems to be working...

Is there a specific API level you're seeing this on?

https://user-images.githubusercontent.com/227486/109942007-a72ece80-7ccb-11eb-8894-c58795e40ac6.mp4

**Comment by qrezet** [comment] 2021-03-04 09:39
hmm.. interesting... in my investigation, it doesn't happen all the time.. I not sure whether this is only encountered because I am using an emulator to test... I'll try and investigate a little more.

**Comment by chrisbanes** [comment] 2021-03-04 09:41
If you can reproduce this reliably let me know, I've just tried about 20 times and it seems to be working ok. `main` branch does use an updated version of `androidx.core:core` though so maybe that's it.

**Comment by chrisbanes** [comment] 2021-03-04 09:55
Going to close this for now, if you can reproduce it let me know.

**Closed by chrisbanes** 2021-03-04 09:55 UTC

**Comment by qrezet** [comment] 2021-03-04 09:57
Will do thank you very much @chrisbanes
