### ISSUE TITLE
[Help] How to use asFile() request Builder

### ISSUE THREAD

**Issue by Shabinder** [chrisbanes/accompanist#173] opened 2020-12-30 12:42 UTC
I am trying to Accomplish Something Like this:

Load Image from a URL asFile then copy that file for later Use and and also load same Image.

If I do following using Drawable the image obtaines as File is of Low Res than original.

```
Glide
            .with(imgView)
            .asFile()
            .load(imgUri)
            .placeholder(R.drawable.ic_song_placeholder)
            .error(R.drawable.ic_musicplaceholder)
            .listener(object:RequestListener<File>{
                override fun onLoadFailed(
                    e: GlideException?,
                    model: Any?,
                    target: Target<File>?,
                    isFirstResource: Boolean
                ): Boolean {
                    log("Glide","LoadFailed")
                    return false
                }

                override fun onResourceReady(
                    resource: File?,
                    model: Any?,
                    target: Target<File>?,
                    dataSource: DataSource?,
                    isFirstResource: Boolean
                ): Boolean {
                    CoroutineScope(Dispatchers.Main).launch {
                            try {
                                val file = File(/*File Path*/)
                                resource?.copyTo(file)
                                Glide.with(imgView)
                                    .load(file)
                                    .placeholder(R.drawable.ic_song_placeholder)
                                    .into(imgView)
                            } catch (e: IOException) {
                                e.printStackTrace()
                            }
                    }
                     return false
                }
            }).submit()
        }
```

**Comment by chrisbanes** [comment] 2020-12-30 12:52
Duplicate of #172

**Closed by chrisbanes** 2020-12-30 12:52 UTC
